name: Build & Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**/*.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: npm install
    - run: npm run doc

    - run: npm install @jsdevtools/npm-publish -g
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./package.json

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        package-path: ./package.json

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.4.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (renovate-bot|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-heat-map@${{steps.create_tag.outputs.versionNumber}}/file/README.md) [![](https://img.shields.io/github/issues/uiwjs/react-heat-map.svg)](https://github.com/uiwjs/react-heat-map/releases) [![](https://img.shields.io/github/forks/uiwjs/react-heat-map.svg)](https://github.com/uiwjs/react-heat-map/network) [![](https://img.shields.io/github/stars/uiwjs/react-heat-map.svg)](https://github.com/uiwjs/react-heat-map/stargazers) [![](https://img.shields.io/github/release/uiwjs/react-heat-map.svg)](https://github.com/uiwjs/react-heat-map/releases) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/@uiw/react-heat-map)](https://bundlephobia.com/result?p=@uiw/react-heat-map@${{steps.create_tag.outputs.versionNumber}})

          ```bash
          npm i @uiw/react-heat-map@${{steps.create_tag.outputs.versionNumber}}
          ```

          ${{ steps.changelog.outputs.compareurl }}

          ${{ steps.changelog.outputs.changelog }}
